-- USED_GOODS_BOARD와 USED_GOODS_USER 테이블에서 완료된 중고 거래의 총금액이 70만 원 이상인 사람의 회원 ID, 닉네임, 총거래금액을 조회하는 SQL문을 작성해주세요. 결과는 총거래금액을 기준으로 오름차순 정렬해주세요.
SELECT USER.USER_ID, USER.NICKNAME, SUM(BOARD.PRICE) AS TOTAL_SALES
FROM USED_GOODS_USER USER 
INNER JOIN  USED_GOODS_BOARD BOARD ON USER.USER_ID = BOARD.WRITER_ID 
WHERE STATUS LIKE 'DONE'
GROUP BY USER.USER_ID HAVING SUM(PRICE) >=700000
ORDER BY TOTAL_SALES ASC;