-- 코드를 입력하세요
SELECT BK.CATEGORY , SUM(SALES) AS TOTAL_SALES
FROM BOOK BK INNER JOIN BOOK_SALES BS ON BK.BOOK_ID = BS.BOOK_ID 
WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') LIKE '2022-01' 
GROUP BY BK.CATEGORY HAVING SUM(SALES)
ORDER BY CATEGORY ASC;